### ISSUE TITLE
Error while running the storybook (npm run storybook)

### ISSUE THREAD

**Issue by jillella** [EvgeniyBudaev/react-typescript-ui#1]
**MacBook-Pro frontend % npm run storybook**             

> frontend@0.1.0 storybook
> start-storybook -p 9009 -s public,src/ui-kit/assets

info @storybook/react v6.5.3
info 
(node:62155) DeprecationWarning: --static-dir CLI flag is deprecated, see:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated---static-dir-cli-flag
(Use `node --trace-deprecation ...` to show where the warning was created)
info => Loading presets
info => Serving static files from ./public at /
info => Serving static files from ./src/ui-kit/assets at /
info => Loading Webpack configuration from `node_modules/react-scripts`
info => Removing existing JavaScript and TypeScript rules.
info => Modifying Create React App rules.
info => Using default Webpack4 setup
ERR! WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
ERR!  - configuration.module.rules[2].oneOf[9].type should be one of these:
ERR!    "javascript/auto" | "javascript/dynamic" | "javascript/esm" | "json" | "webassembly/experimental"
ERR!    -> Module type to use for the module
ERR!     at webpack (/Users/jillella/Documents/GitHub/react-typescript-ui/frontend/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/webpack.js:31:9)
ERR!     at starterGeneratorFn (/Users/jillella/Documents/GitHub/react-typescript-ui/frontend/node_modules/@storybook/builder-webpack4/dist/cjs/index.js:137:18)
ERR!     at starterGeneratorFn.next (<anonymous>)
ERR!     at Object.start (/Users/jillella/Documents/GitHub/react-typescript-ui/frontend/node_modules/@storybook/builder-webpack4/dist/cjs/index.js:275:34)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/Users/jillella/Documents/GitHub/react-typescript-ui/frontend/node_modules/@storybook/core-server/dist/cjs/dev-server.js:207:28)
ERR!     at async buildDevStandalone (/Users/jillella/Documents/GitHub/react-typescript-ui/frontend/node_modules/@storybook/core-server/dist/cjs/build-dev.js:120:31)
ERR!     at async buildDev (/Users/jillella/Documents/GitHub/react-typescript-ui/frontend/node_modules/@storybook/core-server/dist/cjs/build-dev.js:174:5)
ERR!  WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
ERR!  - configuration.module.rules[2].oneOf[9].type should be one of these:
ERR!    "javascript/auto" | "javascript/dynamic" | "javascript/esm" | "json" | "webassembly/experimental"
ERR!    -> Module type to use for the module
ERR!     at webpack (/Users/jillella/Documents/GitHub/react-typescript-ui/frontend/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/webpack.js:31:9)
ERR!     at starterGeneratorFn (/Users/jillella/Documents/GitHub/react-typescript-ui/frontend/node_modules/@storybook/builder-webpack4/dist/cjs/index.js:137:18)
ERR!     at starterGeneratorFn.next (<anonymous>)
ERR!     at Object.start (/Users/jillella/Documents/GitHub/react-typescript-ui/frontend/node_modules/@storybook/builder-webpack4/dist/cjs/index.js:275:34)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/Users/jillella/Documents/GitHub/react-typescript-ui/frontend/node_modules/@storybook/core-server/dist/cjs/dev-server.js:207:28)
ERR!     at async buildDevStandalone (/Users/jillella/Documents/GitHub/react-typescript-ui/frontend/node_modules/@storybook/core-server/dist/cjs/build-dev.js:120:31)
ERR!     at async buildDev (/Users/jillella/Documents/GitHub/react-typescript-ui/frontend/node_modules/@storybook/core-server/dist/cjs/build-dev.js:174:5)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

**Comment by EvgeniyBudaev** [comment]
storybook was deleted from the project
